spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze0ma90c60q6l54lso.mysql.rds.aliyuncs.com:3306/smart-pension-system?useUnicode=true&characterEncoding=UTF-8
    username: yf209
    password: Yf123456
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 2199098121@qq.com
    password: vpkijuodvacldhjj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9000
